### ISSUE TITLE
The HipChat API version has been upgraded to v2

### ISSUE THREAD

**Issue by kkebb** [logstash-plugins/logstash-output-hipchat#5]
As per the subject line, can you please upgrade this plugin to work with API v2 of HipChat?

Thank you!

**Comment by iangkent** [comment]
HipChat Cloud only supports HipChat API v2. Without v2 support this logstash plugin is useless.

**Comment by jordansissel** [comment]
Noted! Hopefully someone will get to this soon :)

**Comment by heytrav** [comment]
Any idea when this might get looked at? I'd actually be quite keen to use it.

**Comment by sukrit007** [comment]
+1 for v2 API support

**Comment by ph** [comment]
version 2.0.0 of the plugin fix this
